# Generated by Django 2.1.8 on 2019-05-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('article_title', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
    ]
