# Generated by Django 2.1.8 on 2019-05-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
