# Generated by Django 2.1.8 on 2019-05-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20190512_1601'),
        ('patient', '0002_auto_20190512_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor'),
        ),
    ]
