# Generated by Django 2.1.8 on 2019-05-27 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_gp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_patients', to='doctor.Doctor'),
        ),
    ]
