# Generated by Django 2.1.8 on 2019-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190512_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
